grails-app/domain/com/nw/pgmchecklist/Answer.groovy
package com.nw.pgmchecklist

class Answer {
	
	String question
	String inputValue
	Boolean answeredYes
	Date dateCreated
	Program program
	Theuser theuser
		

    static constraints = {
		question nullable:false
		inputValue nullable:true
		answeredYes nullable:true
		program nullable:true
		theuser nullable:false
    }
}

grails-app/controllers/com/nw/pgmchecklist/AnswerController.groovy
package com.nw.pgmchecklist



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AnswerController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Answer.list(params), model:[answerInstanceCount: Answer.count()]
    }

    def show(Answer answerInstance) {
        respond answerInstance
    }

    def create() {
        respond new Answer(params)
    }

    @Transactional
    def save(Answer answerInstance) {
        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'create'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'answer.label', default: 'Answer'), answerInstance.id])
                redirect answerInstance
            }
            '*' { respond answerInstance, [status: CREATED] }
        }
    }

    def edit(Answer answerInstance) {
        respond answerInstance
    }

    @Transactional
    def update(Answer answerInstance) {
        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'edit'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Answer.label', default: 'Answer'), answerInstance.id])
                redirect answerInstance
            }
            '*'{ respond answerInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Answer answerInstance) {

        if (answerInstance == null) {
            notFound()
            return
        }

        answerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Answer.label', default: 'Answer'), answerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'answer.label', default: 'Answer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/answer/_form.gsp
<%@ page import="com.nw.pgmchecklist.Answer" %>



<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'question', 'error')} required">
	<label for="question">
		<g:message code="answer.question.label" default="Question" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="question" required="" value="${answerInstance?.question}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'inputValue', 'error')} ">
	<label for="inputValue">
		<g:message code="answer.inputValue.label" default="Input Value" />
		
	</label>
	<g:textField name="inputValue" value="${answerInstance?.inputValue}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'answeredYes', 'error')} ">
	<label for="answeredYes">
		<g:message code="answer.answeredYes.label" default="Answered Yes" />
		
	</label>
	<g:checkBox name="answeredYes" value="${answerInstance?.answeredYes}" />

</div>

<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'program', 'error')} ">
	<label for="program">
		<g:message code="answer.program.label" default="Program" />
		
	</label>
	<g:select id="program" name="program.id" from="${com.nw.pgmchecklist.Program.list()}" optionKey="id" value="${answerInstance?.program?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'theuser', 'error')} required">
	<label for="theuser">
		<g:message code="answer.theuser.label" default="Theuser" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="theuser" name="theuser.id" from="${com.nw.pgmchecklist.Theuser.list()}" optionKey="id" required="" value="${answerInstance?.theuser?.id}" class="many-to-one"/>

</div>

grails-app/views/answer/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-answer" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${answerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${answerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:answerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/answer/edit.gsp
<%@ page import="com.nw.pgmchecklist.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-answer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${answerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${answerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:answerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${answerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/answer/index.gsp
<%@ page import="com.nw.pgmchecklist.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-answer" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="question" title="${message(code: 'answer.question.label', default: 'Question')}" />
					
						<g:sortableColumn property="inputValue" title="${message(code: 'answer.inputValue.label', default: 'Input Value')}" />
					
						<g:sortableColumn property="answeredYes" title="${message(code: 'answer.answeredYes.label', default: 'Answered Yes')}" />
					
						<th><g:message code="answer.program.label" default="Program" /></th>
					
						<th><g:message code="answer.theuser.label" default="Theuser" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'answer.dateCreated.label', default: 'Date Created')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${answerInstanceList}" status="i" var="answerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${answerInstance.id}">${fieldValue(bean: answerInstance, field: "question")}</g:link></td>
					
						<td>${fieldValue(bean: answerInstance, field: "inputValue")}</td>
					
						<td><g:formatBoolean boolean="${answerInstance.answeredYes}" /></td>
					
						<td>${fieldValue(bean: answerInstance, field: "program")}</td>
					
						<td>${fieldValue(bean: answerInstance, field: "theuser")}</td>
					
						<td><g:formatDate date="${answerInstance.dateCreated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${answerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/answer/show.gsp
<%@ page import="com.nw.pgmchecklist.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-answer" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list answer">
			
				<g:if test="${answerInstance?.question}">
				<li class="fieldcontain">
					<span id="question-label" class="property-label"><g:message code="answer.question.label" default="Question" /></span>
					
						<span class="property-value" aria-labelledby="question-label"><g:fieldValue bean="${answerInstance}" field="question"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${answerInstance?.inputValue}">
				<li class="fieldcontain">
					<span id="inputValue-label" class="property-label"><g:message code="answer.inputValue.label" default="Input Value" /></span>
					
						<span class="property-value" aria-labelledby="inputValue-label"><g:fieldValue bean="${answerInstance}" field="inputValue"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${answerInstance?.answeredYes}">
				<li class="fieldcontain">
					<span id="answeredYes-label" class="property-label"><g:message code="answer.answeredYes.label" default="Answered Yes" /></span>
					
						<span class="property-value" aria-labelledby="answeredYes-label"><g:formatBoolean boolean="${answerInstance?.answeredYes}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${answerInstance?.program}">
				<li class="fieldcontain">
					<span id="program-label" class="property-label"><g:message code="answer.program.label" default="Program" /></span>
					
						<span class="property-value" aria-labelledby="program-label"><g:link controller="program" action="show" id="${answerInstance?.program?.id}">${answerInstance?.program?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${answerInstance?.theuser}">
				<li class="fieldcontain">
					<span id="theuser-label" class="property-label"><g:message code="answer.theuser.label" default="Theuser" /></span>
					
						<span class="property-value" aria-labelledby="theuser-label"><g:link controller="theuser" action="show" id="${answerInstance?.theuser?.id}">${answerInstance?.theuser?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${answerInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="answer.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${answerInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:answerInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${answerInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>