grails-app/domain/com/nw/pgmchecklist/Program.groovy
package com.nw.pgmchecklist

class Program {
	String programName
	String progress = "Started"
	Date dateCreated
	Template template
	Theuser theuser
	static hasMany = [answers: Answer]
	
	
    static constraints = {
		programName unique:true
		template nullable:true
		//answers nullable:true
		theuser nullable:false
    }
}

grails-app/domain/com/nw/pgmchecklist/Question.groovy
package com.nw.pgmchecklist

class Question {
	
	String inputType
	String labelText
	Template template

    static constraints = {
		inputType nullable:false
		labelText nullable:false
		template nullable:true
    }
}

grails-app/domain/com/nw/pgmchecklist/Template.groovy
package com.nw.pgmchecklist

class Template {
	String templateName
	Theuser theuser
	static hasMany = [questions: Question]

    static constraints = {
		templateName unique:true
    }
}

grails-app/views/template/_form.gsp
<%@ page import="com.nw.pgmchecklist.Template" %>
<g:javascript src="question-clone.js" />
<g:set var="i" value="${i ?: 0}"/>

<div class="fieldcontain ${hasErrors(bean: templateInstance, field: 'templateName', 'error')} required">
	
	<div class="row">
		<div class="form-group col-md-4">
			<label for="templateName">
				<g:message code="template.templateName.label" default="Template Name" />
				<span class="required-indicator">*</span>
			</label>
			<g:textField class="form-control" name="templateName" required="" value="${templateInstance?.templateName}"/>
		</div>
	</div>
	
	<g:if test="${!questions}">
		<g:render template="newRow"/>
	</g:if>
	<g:each status="i" in="${questions}" var="question">
		<g:render template="newRow" model="['question':question]"/>
	</g:each>
	
	<div class="questions"></div>


</div>

grails-app/views/template/_newRow.gsp
<div id="questionId${i}">
	<div class="row">
		<div class="form-group col-md-2">
			<label>Question:</label>
			
			<g:select class="form-control" name="questionType${i}" from="${questionTypeMap?.entrySet()}" 
      				optionKey="key" optionValue="value" value="${question?.inputType}"/>
		</div>
		
		<div class="form-group col-md-8">
			<label>&nbsp;</label>
			<div class="input-group">
			<g:textField class="form-control" name="questionText${i}" id="questionText${i}" value="${question?.labelText}"/>
			
			<span class="input-group-btn">
				<button type="button" class="add-button btn btn-info" id="add${i}" onclick="cloneDiv(${i})">
					  <span class="icon icon-plus"></span>
					</button>
					<button type="button" class="minus-button btn btn-danger" id="remove${i}" style="display: none;" onclick="removeDiv(${i})">
					  <span class="icon icon-minus"></span>
					</button>
			</span>
			</div>
		</div>

	</div>
	<g:hiddenField name="hiddenQuestionIds" id="hiddenQuestionId${i}" value="${i}" />
	
</div>

grails-app/views/template/_question.gsp
<g:set var="i" value="${i ?: 0}"/>

<div class="fieldcontain ${hasErrors(bean: questionInstance, field: 'inputType', 'error')} required">
	<label for="inputType${i}">
		<g:message code="question.inputType.label" default="Input Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="inputType${i}" id="inputType${i}" required="" value="${questionInstance?.inputType}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: questionInstance, field: 'labelText', 'error')} required">
	<label for="labelText">
		<g:message code="question.labelText.label" default="Label Text" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="labelText${i}" id="labelText${i}" required="" value="${questionInstance?.labelText}"/>

</div>

grails-app/views/template/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'template.label', default: 'Template')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		
		<div id="create-template" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${templateInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${templateInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:templateInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/template/edit.gsp
<%@ page import="com.nw.pgmchecklist.Template" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'template.label', default: 'Template')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		
		<div id="edit-template" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${templateInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${templateInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:templateInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${templateInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/template/index.gsp
<%@ page import="com.nw.pgmchecklist.Template" %>
<%--<%@ page import="com.nw.pgmchecklist.Program" %>--%>
<!DOCTYPE html>
<html>
	<style>
		.tr .th .td .table .thead .tbody{
			box-sizing: border-box;
			display: table;
			border-collapse: collapse;
			position: relative;
			padding:0;
		}
	</style>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'template.label', default: 'Template')}" />
<%--		<g:set var="entityName2" value="${message(code: 'program.label', default: 'Program')}" />--%>
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<ul class="nav nav-tabs">
	<body>
		<div id="list-template" class="content scaffold-list bs-example snippet" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="alert alert-info" role="status">${flash.message}</div>
			</g:if>
			
			
				<ul class="nav nav-tabs">
				<li class="active">
				
				<a href="#1a" data-toggle="tab">Templates</a>
				</li>
				<li>
				<a href="#2a" data-toggle="tab">Review</a>
				</li>
				</ul>
				
				<div class="tab-content clearfix">
				<g:link class="create pull-right" action="create" style="font-size: 20px; text-align: center; width: 15%; background-color: #F47321; color: white; border-radius: 5px;">Create New</g:link>
				<br>
				<br>
				<div class="tab-pane active" id="1a">
				<table class="table table-hover">
				<thead>
					<tr class="table-col-boolean">
						<g:sortableColumn class="table-col-boolean" property="templateName" title="${message(code: 'template.templateName.label', default: 'Template Name')}" />
						<g:sortableColumn class="table-col-boolean" property="templateName" title="${message(code: 'template.templateName.label', default: 'Created By')}" />
						<g:sortableColumn class="table-col-boolean" property="templateName" title="${message(code: 'template.templateName.label', default: 'Options')}" />
					</tr>
				</thead>
				<tbody>
					<g:each in="${templateInstanceList}" status="i" var="templateInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<th class="table-col-boolean"><g:link action="edit" id="${templateInstance.id}">${fieldValue(bean: templateInstance, field: "templateName")}</g:link></th>
							<th class="table-col-boolean">${fieldValue(bean: templateInstance.theuser, field: "username")}</th>
	<%--						<th>--%>
	<%--							<g:link class="template-options" action="edit" id="${templateInstance.id}">Edit</g:link>--%>
	<%--						</th>--%>
							<th class="table-col-boolean">
								<g:form url="[resource:templateInstance, action:'delete']" method="DELETE">
									<fieldset>
										<g:actionSubmit action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
									</fieldset>
								</g:form>
							</th>
						</tr>
					</g:each>
				</tbody>
			</table>
			</div>	
			
			
					
			<div class="tab-pane" id="2a">
				<table class="table table-hover">
				<p>
				Work in progress
				</p>
<%--					<thead>--%>
<%--						<tr>--%>
<%--							<g:sortableColumn property="programName" title="${message(code: 'programName.label', default: 'Program Name')}" />--%>
<%--							<g:sortableColumn code="Program.theuser.label" default="Submitted By" />--%>
<%--							<g:sortableColumn property="dateCreated" title="${message(code: 'dateCreated.label', default: 'Date Submitted')}" />--%>
<%--						</tr>--%>
<%--					</thead>--%>
<%--					<tbody>--%>
<%--						<g:each in="${programInstanceList}" status="i" var="programInstance">--%>
<%--							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">--%>
<%--						--%>
<%--								<td><g:link action="program/index" id="${programInstance.id}">${fieldValue(bean: programInstance, field: "programName")}</g:link></td>--%>
<%--								<td>${fieldValue(bean: programInstance, field: "program.theuser.username")}</td>--%>
<%--								<td>${fieldValue(bean: programInstance, field: "program.dateCreated")}</td>--%>
<%--						--%>
<%--							</tr>--%>
<%--						</g:each>--%>
<%--					</tbody>--%>
				</table>
		
			</div>
			</div>
			</div>
			<div class="pagination">
				<g:paginate total="${templateInstanceCount ?: 0}" />
			</div>
	</body>
	</ul>
</html>

grails-app/views/template/review.gsp
<%@ page import="com.nw.pgmchecklist.Program" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'program.label', default: 'Program')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-program" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="list-program" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:link class="create pull-right" action="create" ><g:message code="default.new.label" args="[entityName]" /></g:link>
			<table class="table table-hover">
			<thead>
					<tr>
						<g:sortableColumn property="programName" title="${message(code: 'program.programName.label', default: 'Program Name')}" />
						<g:sortableColumn code="program.theuser.label" default="Submitted By" />
						<g:sortableColumn property="dateSubmitted" title="${message(code: 'program.dateSubmitted.label', default: 'Date Submitted')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${programInstanceList}" status="i" var="programInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="review" id="${programInstance.id}">${fieldValue(bean: programInstance, field: "programName")}</g:link></td>
						<td>${fieldValue(bean: programInstance, field: "theuser.username")}</td>
						<td>${fieldValue(bean: programInstance, field: "dateSubmitted")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${programInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>